name: Deprecated Check

on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Check for deprecated functions
        run: |
          deprecated=true
          if [[ $deprecated == true ]]; then
            # This creates a warning annotation in GitHub
            echo "::warning file=src/test.sh,line=1,col=1::Deprecated function found"
          fi
